### ISSUE TITLE
wait_for_update should be at least 100ms

### ISSUE THREAD

**Issue by philpott** [pieeyeinc/pieeye-gtm-template#5]
https://github.com/pieeyeinc/pieeye-gtm-template/blob/1b5fbeaa0b261c3b2f4dc18c7cb2f1b6811a0f39/template.tpl#L219

When reviewing your template we've noticed that wait_for_update was set to a default less than 500 milliseconds. When specifying this it's a best practice to give some buffer time to attempt to allow for the updateConsent command to be fired. This is very important when loading the consent management script dynamically.

**Comment by naeem-epi** [comment]
I have added `wait_for_update` at least 200 ms
Please review
