### ISSUE TITLE
Consider providing the option to dynamically install the CMP

### ISSUE THREAD

**Issue by philpott** [pieeyeinc/pieeye-gtm-template#6]
When reviewing the template we noticed that the template is only configuring consent settings. Have you considered also providing the option to install the CMP through the template using injectScript? This helps to simplify the installation of the CMP removing the necessity for adding any on-page code and simplifying consent mode setup.

**Comment by naeem-epi** [comment]
Thank you for your suggestion regarding the injectScript using CMP template. Currently, our template is focused on configuring consent settings.

Most of our customers use CMS platforms such as Shopify, BigCommerce, and others. These platforms have built-in capabilities for script injection, which manage the script integration seamlessly. By leveraging the native features of these platforms, we ensure a streamlined and secure setup process for our users.

We appreciate your feedback and will keep this functionality in mind for future updates to further enhance user experience.
